name: Pull Request Actions
on:
  push:
    branches: [main, next]
  pull_request:
    types: [ready_for_review, opened, synchronize]
    branches: [main, next]
  workflow_dispatch:
    permissions:

env:
  NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
jobs:
  setup:
    if: "! github.event.pull_request.draft"
    runs-on: ubuntu-latest
    timeout-minutes: 8
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Cache node modules
        id: cache-node-modules
        uses: actions/cache@v3
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json')}}-${{ steps.branch-name.outputs.current_branch }}
      - name: Install Dependencies
        run: npm ci && cd ./packages/web-components && npx playwright install --with-deps
      - name: Build
        run: npm run build
  e2e:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Get Cache
        uses: actions/cache@v3
        id: get-cache
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json')}}-${{ steps.branch-name.outputs.current_branch }}
      - name: e2e Tests
        run: npm run test.e2e.ci
        working-directory: ./packages/web-components
  VRTs:
    needs: setup
    runs-on: ubuntu-latest
    timeout-minutes: 7
    steps:
      - uses: actions/checkout@v2
      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v6
      - name: Get Cache
        uses: actions/cache@v3
        id: get-cache
        with:
          path: |
            ./packages/web-components/node_modules
            ./packages/web-components/dist
          key: ${{ runner.os }}-setup-${{ hashFiles('./packages/web-components/package-lock.json')}}-${{ steps.branch-name.outputs.current_branch }}
      - name: Run VRTs
        run: npm run test.vrt
        working-directory: ./packages/web-components
